#!/usr/bin/env node

var path = require('path');
var express = require('express');

var app = express();
var PORT = parseInt(process.env.DASHBOARD_LAB_PORT || '4173', 10);
var BASE_PATH = normalizeBasePath(process.env.DASHBOARD_LAB_BASE_PATH || '/ghost/email');
var PUBLIC_DIR = path.join(__dirname, 'public');

function normalizeBasePath(input) {
  var base = String(input || '/ghost/email').trim();
  if (!base.startsWith('/')) base = '/' + base;
  if (base.length > 1) {
    base = base.replace(/\/+$/, '');
  }
  return base;
}

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function jitter(base, percent) {
  var variance = Math.max(1, Math.round(base * percent));
  return Math.max(0, base + randomInt(-variance, variance));
}

function pick(values) {
  return values[randomInt(0, values.length - 1)];
}

function parsePreset(req) {
  var preset = String(req.query.preset || 'healthy').toLowerCase();
  if (preset !== 'healthy' && preset !== 'incident' && preset !== 'warmup') {
    return 'healthy';
  }
  return preset;
}

function buildSummary(preset) {
  if (preset === 'incident') {
    var sentIncident = jitter(420, 0.1);
    var failedIncident = jitter(47, 0.25);
    var complainedIncident = jitter(11, 0.3);
    return {
      sent_24h: sentIncident,
      delivered_24h: Math.max(0, sentIncident - failedIncident - complainedIncident - jitter(9, 0.4)),
      opened_24h: jitter(140, 0.25),
      clicked_24h: jitter(28, 0.25),
      failed_24h: failedIncident,
      complained_24h: complainedIncident,
      suppressions: {
        bounces: jitter(83, 0.15),
        complaints: jitter(18, 0.2),
        unsubscribes: jitter(45, 0.18)
      }
    };
  }

  if (preset === 'warmup') {
    var sentWarmup = jitter(66, 0.22);
    return {
      sent_24h: sentWarmup,
      delivered_24h: Math.max(0, sentWarmup - jitter(2, 0.5)),
      opened_24h: jitter(21, 0.35),
      clicked_24h: jitter(4, 0.5),
      failed_24h: jitter(1, 1),
      complained_24h: jitter(0, 1),
      suppressions: {
        bounces: jitter(3, 0.7),
        complaints: jitter(1, 1),
        unsubscribes: jitter(5, 0.5)
      }
    };
  }

  var sentHealthy = jitter(285, 0.13);
  var failedHealthy = jitter(4, 0.6);
  var complainedHealthy = jitter(1, 1);
  return {
    sent_24h: sentHealthy,
    delivered_24h: Math.max(0, sentHealthy - failedHealthy - complainedHealthy - jitter(3, 0.5)),
    opened_24h: jitter(115, 0.2),
    clicked_24h: jitter(31, 0.2),
    failed_24h: failedHealthy,
    complained_24h: complainedHealthy,
    suppressions: {
      bounces: jitter(22, 0.25),
      complaints: jitter(5, 0.35),
      unsubscribes: jitter(12, 0.3)
    }
  };
}

function buildHealth(preset, pathName) {
  var now = new Date();
  var pollLagSeconds = preset === 'incident' ? randomInt(70, 190) : randomInt(3, 30);
  var lastPoll = new Date(now.getTime() - pollLagSeconds * 1000);

  return {
    status: preset === 'incident' ? 'degraded' : 'ok',
    service: 'ghost-mail-bridge',
    mode: 'local-lab',
    timestamp: now.toISOString(),
    path: pathName,
    tables: {
      message_map: jitter(121, 0.1),
      recipient_emails: jitter(286, 0.1),
      events: jitter(912, 0.1),
      suppressions: jitter(42, 0.15)
    },
    poller: {
      startedAt: new Date(now.getTime() - 1000 * 60 * 24).toISOString(),
      lastPollStartedAt: lastPoll.toISOString(),
      lastPollFinishedAt: lastPoll.toISOString(),
      lastErrorAt: preset === 'incident' ? new Date(now.getTime() - randomInt(10, 240) * 1000).toISOString() : null,
      lastErrorMessage: preset === 'incident' ? 'SQS receive timeout reached and retried' : '',
      lastMessagesReceived: preset === 'incident' ? randomInt(0, 2) : randomInt(0, 6),
      totalMessagesReceived: jitter(3500, 0.08),
      totalEventsStored: jitter(3300, 0.08),
      isRunning: true
    }
  };
}

function buildFailures(preset, limit) {
  var nowEpoch = Math.floor(Date.now() / 1000);
  var count = 0;

  if (preset === 'incident') count = randomInt(10, 24);
  if (preset === 'healthy') count = randomInt(0, 6);
  if (preset === 'warmup') count = randomInt(0, 2);

  count = clamp(count, 0, limit);

  var failedReasons = [
    'Mailbox unavailable',
    'Message rejected by recipient policy',
    'User unknown',
    'Domain has no valid MX records',
    'Mailbox full',
    'Temporary DNS failure'
  ];

  var complaintReasons = [
    'Feedback loop complaint from recipient',
    'Abuse report generated by mailbox provider',
    'Message marked as spam by recipient'
  ];

  var rows = [];
  for (var i = 0; i < count; i++) {
    var isComplaint = preset === 'incident' ? Math.random() < 0.33 : Math.random() < 0.2;
    var event = isComplaint ? 'complained' : 'failed';
    var minutesAgo = randomInt(2 + i * 3, 220 + i * 6);
    var reason = isComplaint ? pick(complaintReasons) : pick(failedReasons);

    rows.push({
      id: 'mock-' + preset + '-' + i,
      event: event,
      severity: event === 'failed' ? (Math.random() < 0.7 ? 'permanent' : 'temporary') : null,
      recipient: 'recipient+' + (1000 + i) + '@example.net',
      timestamp: nowEpoch - minutesAgo * 60,
      message_id: 'mock-message-' + randomInt(100000, 999999),
      email_id: 'mock-email-' + randomInt(1000, 9999),
      code: event === 'failed' ? pick([421, 450, 550, 554]) : null,
      reason: reason,
      enhanced_code: event === 'failed' ? pick(['4.2.1', '4.4.1', '5.1.1', '5.7.1']) : null
    });
  }

  rows.sort(function(a, b) {
    return b.timestamp - a.timestamp;
  });

  return rows;
}

function parseLimit(req) {
  var limit = parseInt(req.query.limit, 10);
  if (!Number.isFinite(limit) || limit <= 0) return 25;
  return clamp(limit, 1, 200);
}

app.use(function(_req, res, next) {
  res.setHeader('Cache-Control', 'no-store');
  next();
});

app.get('/', function(_req, res) {
  res.redirect(BASE_PATH);
});

app.use(BASE_PATH, express.static(PUBLIC_DIR));

app.get(BASE_PATH + '/api/summary', function(req, res) {
  var preset = parsePreset(req);
  res.json(buildSummary(preset));
});

app.get(BASE_PATH + '/api/health', function(req, res) {
  var preset = parsePreset(req);
  res.json(buildHealth(preset, BASE_PATH));
});

app.get(BASE_PATH + '/api/failures', function(req, res) {
  var preset = parsePreset(req);
  var limit = parseLimit(req);
  res.json({
    items: buildFailures(preset, limit)
  });
});

app.get(BASE_PATH + '/api/presets', function(_req, res) {
  res.json({
    items: [
      { id: 'healthy', label: 'Healthy traffic' },
      { id: 'warmup', label: 'Low volume warm-up' },
      { id: 'incident', label: 'Incident mode' }
    ]
  });
});

app.listen(PORT, function() {
  console.log('Ghost Mail Bridge local dashboard lab');
  console.log('  URL: http://localhost:' + PORT + BASE_PATH);
  console.log('  Base path: ' + BASE_PATH);
  console.log('  Tip: run with `node --watch .local-dev/dashboard-lab/server.js` for live reload');
});
